# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "local" ]
  pull_request:
    branches: [ "local" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: install sdk
      run: dotnet-install.ps1

Get-Help ./dotnet-install.ps1
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      continue-on-error: true
      run: dotnet build --no-restore
    - name: Test
      continue-on-error: true
      run: dotnet test --no-build --verbosity normal
